package it.unirc.pwm.ht.prodotto;
// Generated 20 nov 2021, 18:11:58 by Hibernate Tools 5.4.12.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Prodotto generated by hbm2java
 */
public class Prodotto implements java.io.Serializable {

	private int idprodotto;
	private String nome;
	private String marca;
	private float prezzo;
	private String genere;
	private int taglia;
	private String colore;
	private int quantita;
	private Set ordines = new HashSet(0);
	private String tipo_cliente;


	public Prodotto() {
	}

	public Prodotto(int idprodotto, String nome, String marca, float prezzo, String genere, int taglia, String colore,
			int quantita) {
		this.idprodotto = idprodotto;
		this.nome = nome;
		this.marca = marca;
		this.prezzo = prezzo;
		this.genere = genere;
		this.taglia = taglia;
		this.colore = colore;
		this.quantita = quantita;
	}



	public Prodotto(int idprodotto, String nome, String marca, float prezzo, String genere, int taglia, String colore,
			int quantita, Set ordines, String tipo_cliente) {
		super();
		this.idprodotto = idprodotto;
		this.nome = nome;
		this.marca = marca;
		this.prezzo = prezzo;
		this.genere = genere;
		this.taglia = taglia;
		this.colore = colore;
		this.quantita = quantita;
		this.ordines = ordines;
		this.tipo_cliente = tipo_cliente;
	}

	public int getIdprodotto() {
		return this.idprodotto;
	}

	public void setIdprodotto(int idprodotto) {
		this.idprodotto = idprodotto;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public float getPrezzo() {
		return this.prezzo;
	}

	public void setPrezzo(float prezzo) {
		this.prezzo = prezzo;
	}

	public String getGenere() {
		return this.genere;
	}

	public void setGenere(String genere) {
		this.genere = genere;
	}

	public int getTaglia() {
		return idprodotto;
	}

	public void setTaglia(int taglia) {
		this.taglia = taglia;
	}

	public String getColore() {
		return this.colore;
	}

	public void setColore(String colore) {
		this.colore = colore;
	}

	public int getQuantita() {
		return this.quantita;
	}

	public void setQuantita(int quantita) {
		this.quantita = quantita;
	}

	public Set getOrdines() {
		return this.ordines;
	}

	public void setOrdines(Set ordines) {
		this.ordines = ordines;
	}

	public Serializable getIdcliente() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getTipo_cliente() {
		return tipo_cliente;
	}

	public void setTipo_cliente(String tipo_cliente) {
		this.tipo_cliente = tipo_cliente;
	}

	@Override
	public String toString() {
		return "Prodotto [idprodotto=" + idprodotto + ", nome=" + nome + ", marca=" + marca + ", prezzo=" + prezzo
				+ ", genere=" + genere + ", taglia=" + taglia + ", colore=" + colore + ", quantita=" + quantita
				+ ", tipo_cliente=" + tipo_cliente + "]";
	}

	
	
	

}
