package it.unirc.pwm.ht.account;
// Generated 30 mag 2022, 12:25:21 by Hibernate Tools 5.4.12.Final

import it.unirc.pwm.ht.cliente.Cliente;
import it.unirc.pwm.ht.titolare.Titolare;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private int id;
	private String email;
	private String password;
	private String numero;
	private Titolare titolare;
	private Cliente cliente;

	public Account() {
	}

	public Account(int id, String email, String password, String numero) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.numero = numero;
	}

	public Account(int id, String email, String password, String numero, Titolare titolare, Cliente cliente) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.numero = numero;
		this.titolare = titolare;
		this.cliente = cliente;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Titolare getTitolare() {
		return this.titolare;
	}

	public void setTitolare(Titolare titolare) {
		this.titolare = titolare;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

}
