package it.unirc.pwm.ht.account;
// Generated 20 nov 2021, 18:11:58 by Hibernate Tools 5.4.12.Final
//AAAAA
import it.unirc.pwm.ht.cliente.Cliente;
import it.unirc.pwm.ht.titolare.Titolare;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Cliente cliente;
	private Titolare titolare;
	private String email;
	private String password;
	private String numero;

	public Account() {
	}

	public Account(Cliente cliente, Titolare titolare, String email, String password, String numero) {
		this.cliente = cliente;
		this.titolare = titolare;
		this.email = email;
		this.password = password;
		this.numero = numero;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Titolare getTitolare() {
		return this.titolare;
	}

	public void setTitolare(Titolare titolare) {
		this.titolare = titolare;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

}
