package it.unirc.pwm.ht.titolare;
// Generated 20 nov 2021, 18:11:58 by Hibernate Tools 5.4.12.Final

import java.io.Serializable;

import it.unirc.pwm.ht.account.Account;

/**
 * Titolare generated by hbm2java
 */
public class Titolare implements java.io.Serializable {

	private int idtitolare;
	private String nome;
	private String cognome;
	private int capitale;
	private String CF;
	private Account account;

	public Titolare() {
	}

	public Titolare(int idtitolare, String nome, String cognome, int capitale, String CF) {
		this.idtitolare = idtitolare;
		this.nome = nome;
		this.cognome = cognome;
		this.capitale = capitale;
		this.CF = CF;
	}

	public Titolare(int idtitolare, String nome, String cognome, int capitale, String CF, Account account) {
		this.idtitolare = idtitolare;
		this.nome = nome;
		this.cognome = cognome;
		this.capitale = capitale;
		this.CF = CF;
		this.account = account;
	}

	public int getIdtitolare() {
		return this.idtitolare;
	}

	public void setIdtitolare(int idtitolare) {
		this.idtitolare = idtitolare;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public int getCapitale() {
		return this.capitale;
	}

	public void setCapitale(int capitale) {
		this.capitale = capitale;
	}

	public String getCF() {
		return this.CF;
	}

	public void setCF(String CF) {
		this.CF = CF;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Serializable getIdcliente() {
		// TODO Auto-generated method stub
		return null;
	}

}
