package it.unirc.pwm.ht.titolare;
// Generated 30 mag 2022, 12:25:21 by Hibernate Tools 5.4.12.Final

import it.unirc.pwm.ht.account.Account;

/**
 * Titolare generated by hbm2java
 */
public class Titolare implements java.io.Serializable {

	private int idtitolare;
	private Account account;
	private String nome;
	private String cognome;
	private int capitale;
	private String CF;

	public Titolare() {
	}

	public Titolare(Account account, String nome, String cognome, int capitale, String CF) {
		this.account = account;
		this.nome = nome;
		this.cognome = cognome;
		this.capitale = capitale;
		this.CF = CF;
	}

	public int getIdtitolare() {
		return this.idtitolare;
	}

	public void setIdtitolare(int idtitolare) {
		this.idtitolare = idtitolare;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public int getCapitale() {
		return this.capitale;
	}

	public void setCapitale(int capitale) {
		this.capitale = capitale;
	}

	public String getCF() {
		return this.CF;
	}

	public void setCF(String CF) {
		this.CF = CF;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((CF == null) ? 0 : CF.hashCode());
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		result = prime * result + capitale;
		result = prime * result + ((cognome == null) ? 0 : cognome.hashCode());
		result = prime * result + idtitolare;
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Titolare other = (Titolare) obj;
		if (CF == null) {
			if (other.CF != null)
				return false;
		} else if (!CF.equals(other.CF))
			return false;
		if (account == null) {
			if (other.account != null)
				return false;
		} else if (!account.equals(other.account))
			return false;
		if (capitale != other.capitale)
			return false;
		if (cognome == null) {
			if (other.cognome != null)
				return false;
		} else if (!cognome.equals(other.cognome))
			return false;
		if (idtitolare != other.idtitolare)
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Titolare [idtitolare=" + idtitolare + ", account=" + account + ", nome=" + nome + ", cognome=" + cognome
				+ ", capitale=" + capitale + ", CF=" + CF + "]";
	}


}
