package it.unirc.pwm.ht.cliente;
// Generated 30 mag 2022, 12:25:21 by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import it.unirc.pwm.ht.account.Account;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idcliente;
	private Account account;
	private String nome;
	private String cognome;
	private Date datanascita;
	private String CF;
	private String iban;
	private String PIva;
	private Set ordines = new HashSet(0);

	public Cliente() {
	}

	public Cliente(Account account, String nome, String cognome, Date datanascita, String CF, String iban,
			String PIva) {
		this.account = account;
		this.nome = nome;
		this.cognome = cognome;
		this.datanascita = datanascita;
		this.CF = CF;
		this.iban = iban;
		this.PIva = PIva;
	}

	public Cliente(Account account, String nome, String cognome, Date datanascita, String CF, String iban, String PIva,
			Set ordines) {
		this.account = account;
		this.nome = nome;
		this.cognome = cognome;
		this.datanascita = datanascita;
		this.CF = CF;
		this.iban = iban;
		this.PIva = PIva;
		this.ordines = ordines;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public Date getDatanascita() {
		return this.datanascita;
	}

	public void setDatanascita(Date datanascita) {
		this.datanascita = datanascita;
	}

	public String getCF() {
		return this.CF;
	}

	public void setCF(String CF) {
		this.CF = CF;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public String getPIva() {
		return this.PIva;
	}

	public void setPIva(String PIva) {
		this.PIva = PIva;
	}

	public Set getOrdines() {
		return this.ordines;
	}

	public void setOrdines(Set ordines) {
		this.ordines = ordines;
	}
}
