package it.unirc.pwm.ht.ordine;
// Generated 30 mag 2022, 12:25:21 by Hibernate Tools 5.4.12.Final

import it.unirc.pwm.ht.prodotto.Prodotto;

/**
 * OrdineProdotto generated by hbm2java
 */
public class OrdineProdotto implements java.io.Serializable {

	private OrdineProdottoId id;
	private Ordine ordine;
	private Prodotto prodotto;

	public OrdineProdotto() {
	}

	public OrdineProdotto(OrdineProdottoId id, Ordine ordine, Prodotto prodotto) {
		this.id = id;
		this.ordine = ordine;
		this.prodotto = prodotto;
	}

	public OrdineProdottoId getId() {
		return this.id;
	}

	public void setId(OrdineProdottoId id) {
		this.id = id;
	}

	public Ordine getOrdine() {
		return this.ordine;
	}

	public void setOrdine(Ordine ordine) {
		this.ordine = ordine;
	}

	public Prodotto getProdotto() {
		return this.prodotto;
	}

	public void setProdotto(Prodotto prodotto) {
		this.prodotto = prodotto;
	}

}
