package it.unirc.pwm.ht.ordine;
// Generated 20 nov 2021, 18:11:58 by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import it.unirc.pwm.ht.cliente.Cliente;

/**
 * Ordine generated by hbm2java
 */
public class Ordine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idordine;
	private Cliente cliente;
	private int quantita;
	private Date data;
	private Set prodottos = new HashSet(0);

	public Ordine() {
	}

	public Ordine(int idordine, int quantita, Date data) {
		this.idordine = idordine;
		this.quantita = quantita;
		this.data = data;
	}

	public Ordine(int idordine, Cliente cliente, int quantita, Date data, Set prodottos) {
		this.idordine = idordine;
		this.cliente = cliente;
		this.quantita = quantita;
		this.data = data;
		this.prodottos = prodottos;
	}

	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public int getQuantita() {
		return this.quantita;
	}

	public void setQuantita(int quantita) {
		this.quantita = quantita;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Set getProdottos() {
		return this.prodottos;
	}

	public void setProdottos(Set prodottos) {
		this.prodottos = prodottos;
	}

}
