package it.unirc.pwm.ht.ordine;
// Generated 30 mag 2022, 12:25:21 by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import it.unirc.pwm.ht.cliente.Cliente;

/**
 * Ordine generated by hbm2java
 */
public class Ordine implements java.io.Serializable {

	private int idordine;
	private Cliente cliente;
	private Integer cumulativoOrdine;
	private int quantita;
	private Date data;
	private Set ordineProdottos = new HashSet(0);

	public Ordine() {
	}

	public Ordine(int idordine, int quantita, Date data) {
		this.idordine = idordine;
		this.quantita = quantita;
		this.data = data;
	}

	public Ordine(int idordine, Cliente cliente, Integer cumulativoOrdine, int quantita, Date data,
			Set ordineProdottos) {
		this.idordine = idordine;
		this.cliente = cliente;
		this.cumulativoOrdine = cumulativoOrdine;
		this.quantita = quantita;
		this.data = data;
		this.ordineProdottos = ordineProdottos;
	}

	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Integer getCumulativoOrdine() {
		return this.cumulativoOrdine;
	}

	public void setCumulativoOrdine(Integer cumulativoOrdine) {
		this.cumulativoOrdine = cumulativoOrdine;
	}

	public int getQuantita() {
		return this.quantita;
	}

	public void setQuantita(int quantita) {
		this.quantita = quantita;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Set getOrdineProdottos() {
		return this.ordineProdottos;
	}

	public void setOrdineProdottos(Set ordineProdottos) {
		this.ordineProdottos = ordineProdottos;
	}

}
