package it.unirc.pwm.ht.ordine;
// Generated 30 mag 2022, 12:25:21 by Hibernate Tools 5.4.12.Final

/**
 * OrdineProdottoId generated by hbm2java
 */
public class OrdineProdottoId implements java.io.Serializable {

	private int idordine;
	private int idprod;

	public OrdineProdottoId() {
	}

	public OrdineProdottoId(int idordine, int idprod) {
		this.idordine = idordine;
		this.idprod = idprod;
	}

	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	public int getIdprod() {
		return this.idprod;
	}

	public void setIdprod(int idprod) {
		this.idprod = idprod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdineProdottoId))
			return false;
		OrdineProdottoId castOther = (OrdineProdottoId) other;

		return (this.getIdordine() == castOther.getIdordine()) && (this.getIdprod() == castOther.getIdprod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdordine();
		result = 37 * result + this.getIdprod();
		return result;
	}

}
